name: CI/CD Pipeline for cATO Dashboard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install cfn-lint
        run: |
          python -m pip install --upgrade pip
          pip install cfn-lint
          
      - name: Run CloudFormation Linting
        run: |
          cfn-lint cloudformation/*.yaml
          
      - name: Upload linting results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cfn-lint-results
          path: cfn-lint-results.txt
  
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi
          pip install boto3 mock
          
      - name: Run tests
        run: |
          python -m pytest tests/test_lambda_function.py tests/test_custom_resource.py -v
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/*.py
          
  deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Run deployment script
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh 